language: ruby
rvm:
- 2.4.4
install:
- "./bin/setup"
script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --assume-extension --url-ignore "/(\w+\/)?feed.xml/"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: xxxnell
  - EMAIL: xxxxxnell@gmail.com
  - secure: QniLS14q8xkdgO+FI4+iPducdPVfUGGDUJMYiJcvE2r1+otEUeIfOekX7gn+KzH7HQb/cQCvI2wPMc93YT9//n/upHHzM43ydV8Pq8s8vMX7bx7U4JPujID/+Ll3j+6SdoGvf+RdquDSKAMCMfPDXRnDqy6GCeWJ3LP9hTAMKEXQf13owsQ4/sUENQy255MYhNNTsUms7AuvmNf9HZLbyMKz2V7mKXLvDTaDWAGFQ8NngtL3alukjPVjM3RMWXKH8gTBZaMFtesK9+3Oe2DZYHu2LaIeUd6LYJrdmdNgdXyhpziPnP4ML5y+mdOP5t77R6zSi5gulfz1d9wlr/exbY4r408vN87np6VwASNsOZIehjrIo+B6mTrE9cuWKk/KwNIABly2ohLJPx8bl9Y5sef0QFVt/DSEmfmLf1zH5thEMRRYbBzmfNvpbNDTWquzapqO/pfrPf07buqGYbFm4Cim4W5IBNG3CaEotAIDgz0bJDtWOp7DCMUOAtGCMPDrteODKxl2WP0alEkvyeaeE/Fnqxi+O/GrgPa55alCDksaPXvy+Wsaz/0+nTJdd28YBgwseZJ5rdkgHK2NU6kZr3TkDmJBFzbKXY8UYVAf1P4WC8HEGxjFEoV4HcrzRkW10xIqqSF2kFwenmBXdjp5p4ig0WV9YyzD1C1zHtOFHh4=
